spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: openai/gpt-oss-120b    
          temperature: 0.2
      audio:
        transcription:
          options:
            model: whisper-large-v3-turbo
            language: pt