# Opcional: use com  mvn spring-boot:run -Dspring-boot.run.profiles=postgres  (requer docker-compose.yml ou um Postgres próprio)
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smartfinance}
    username: ${DB_USER:smart}
    password: ${DB_PASSWORD:smart123}
  h2:
    console:
      enabled: false
